services:
  - type: web
    name: monitor-publico
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r dashboard/requirements.txt
    startCommand: cd dashboard && gunicorn app:server --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: GCP_CREDENTIALS
        sync: false  # VocÃª vai configurar manualmente no painel do Render
